### ISSUE TITLE
Plan for v4 release

### ISSUE THREAD

**Issue by chriskrycho** [ember-modifier/ember-modifier#203]
An outline of what I think needs to be done for a v4 release:

- [x] Update the types to use the latest (see #187 and #194: Dependabot is, quite reasonably, not smart enough to do this itself): #209
- [x] Convert this to an Embroider v2 addon (#296)
- [x] Update the class-based modifier API to bring it in line with the rest of the framework
    - [x] In class-based modifiers, make the `element` and args (`positional` and `named`) arguments to the relevant methods, making the modifier APIs basically identical to the helper APIs, just with the addition of the `element` argument, and do not eagerly consume args in the new API: #217
    - [x] Deprecate using legacy lifecycle hooks #220
    - [x] Deprecate accessing `this.element` or `this.args` *(depends on previous step)* #221
    - [x] Remove `this.element` and `this.args` *(at release)* #244
- [x] Update function-based modifiers not to always consume args eagerly
    - [x] introduce an `eager` option to `modifier()` #222
    - [x] deprecate calling `modifier()` without `{ eager: false }` #223 
- [x] Update the "signature" for modifiers in general to match what we're doing in emberjs/rfcs#748
    - [x] introduce a `Signature` type with an `Args` field `Named` and `Positional`: #210 
    - [x] deprecate use of the signature which uses the classic `Args` form with `named` and `positional` *(depends on previous step)*
    - [x] drop support for the previous signature *(at release)* #244
- [x] Switch from `willDestroy` to using the destroyables API
    - [x] deprecate `willDestroy` in favor of using `registerDestructor` #212
    - [x] update docs and examples accordingly
    - [x] remove `willDestroy` hook *(at release)* #244
- [x] Drop Node 12 #238

There are two big switches here:

1. Switch away from having `element` and `args` set on the backing class, and aligning it with the way that class-based helpers work. This is intentional: modifiers are *very* similar to helpers in how they work—in a real sense, they are just a different kind of helper: one that receives an `Element` as an argument, and has different constraints about when and how it gets run. The point of the API changes here is to reflect that.

    This allows us to make the API surface of a class-based modifier much more minimal, and to then guide users to simply make use of (both tracked and untracked) state within the modifier class—just like they would with helpers or component backing classes!

2. Stop consuming `args` eagerly. Instead, behave like autotracking does in general: only entangle what the end user *actually uses*.

There are also two open questions:

- Is there any value to having *both* `didReceiveArguments` *and* `didUpdateArguments`? My own opinion is *no* (and the outline of the class below is updated accordingly)
- Given that `didInstall` is called *after* `didReceiveArguments`, with the same arguments, is there any reason to maintain *that* hook, rather than just guiding users to do standard first-time-installation behavior (the same as we would otherwise)? My opinion here is *also* no, but I don't feel quite as strongly about that as I do about `didReceiveArguments` and `didUpdateArguments`, so I’ve left it there *for now*.

---

The new signature interface (which can be straightforwardly expanded into an `Invokable` signature per the Component signature RFC):

```ts
interface ModifierSignature {
  Args?: {
    Named?: {
      [argName: string]: unknown;
    };
    Positional: unknown[];
  };
  // defaults to `Element` if not supplied
  Element?: Element;
}
```

The updated class-based modifier signature (assuming some type helpers which we will make available):

```ts
export default class ClassBasedModifier<S> {
  constructor(
    owner: unknown,
    args: {
      positional: PositionalArgs<S>;
      named: NamedArgs<S>;
    }
  );

  modify(
    element: ElementFor<S>,
    positional: PositionalArgs<S>,
    named: NamedArgs<S>
  ): void;
}
```

The updated function-based modifier signature:

```ts
function modifier<
  S,
  E extends ElementFor<S> = ElementFor<S>,
  P extends PositionalArgs<S> = PositionalArgs<S>,
  N extends NamedArgs<S> = NamedArgs<S>
>(
  fn: (el: E, pos: P, named: N) => void
): InvokableModifier<{
  Element: E,
  Args: {
    Named: N;
    Positional: P;
  };
}>;
```

The thing I have written as `InvokableModifier` here is an opaque type representing the result of creating a modifier this way, and is useful to e.g. Glint for capturing the type of the resulting modifier. The reason for writing it this way is that it lets you define a modifier *either* with an exported `Signature` interface *or* directly inline.

With a signature:

```ts
interface PlaySig {
  Args: {
    Named: {
      when: boolean;
    };
  };
  Element: HTMLMediaElement;
}

const playWithSig = modifier<PlaySig>((el, _, { when: shouldPlay }) => {
  if (shouldPlay) {
    el.play();
  } else {
    el.pause();
  };
});
```

Inline:

```ts
const playInline = modifier(
  (
    el: HTMLMediaElement,
    _: [],
    { when: shouldPlay}: { when: boolean }
  ) => {
    if (shouldPlay) {
      el.play();
    } else {
      el.pause();
    }
  }
);
```

**Comment by chriskrycho** [comment]
@SergeAstapov let me know if you feel like knocking out the v2 addon conversion sometime this month—I’m probably not going to touch this for a few weeks *at least*, now that all the types work is done, but would welcome a PR that does that here.

**Comment by SergeAstapov** [comment]
@chriskrycho sure! I'll create PR to do that convertion next week

**Comment by SergeAstapov** [comment]
@chriskrycho v2 addon PR is done - #296

I think it worth publishing v4 beta as you can't just point to github from package.json any more as addon code is hosted in the folder *and* authoring format requires build step for the addon to be consumed in the app.

**Comment by chriskrycho** [comment]
Thank you! I will take a look by the end of the week!

**Comment by chriskrycho** [comment]
All right, this is done. I’ll tentatively plan to cut a v4 beta release in the next few days.

**Comment by chriskrycho** [comment]
[v4.0.0-beta.0](https://github.com/ember-modifier/ember-modifier/releases/tag/v4.0.0-beta.0) 🎉

**Comment by SergeAstapov** [comment]
@chriskrycho looks like that release didn't get to npm, could you please publish to npm?

**Comment by chriskrycho** [comment]
Hmmm, weird – I will do so, thanks!

**Comment by chriskrycho** [comment]
Properly published [v4.0.0-beta.1](https://www.npmjs.com/package/ember-modifier/v/4.0.0-beta.1).
